<?php
return array (
  'con_acc_desc.apple' => 'To setup Sign in with Apple, a paid <a href="https://developer.apple.com/programs/enroll/" target="_blank">Apple Developer membership</a> is required. For more information on the setup process, please see the <a href="https://xenforo.com/goto/apple-help" target="_blank">XenForo manual</a>.',
  'con_acc_desc.facebook' => '',
  'con_acc_desc.github' => '',
  'con_acc_desc.google' => '',
  'con_acc_desc.linkedin' => '',
  'con_acc_desc.microsoft' => '',
  'con_acc_desc.th_cap_amazon' => '',
  'con_acc_desc.th_cap_amazoncognito' => '',
  'con_acc_desc.th_cap_apple' => '',
  'con_acc_desc.th_cap_battlenet' => '',
  'con_acc_desc.th_cap_deviantart' => '',
  'con_acc_desc.th_cap_discord' => '',
  'con_acc_desc.th_cap_dropbox' => '',
  'con_acc_desc.th_cap_epicgames' => '',
  'con_acc_desc.th_cap_imgur' => '',
  'con_acc_desc.th_cap_imis' => '',
  'con_acc_desc.th_cap_instagram' => '',
  'con_acc_desc.th_cap_keycloak' => '',
  'con_acc_desc.th_cap_miniorange' => '',
  'con_acc_desc.th_cap_paypal' => '',
  'con_acc_desc.th_cap_pinterest' => '',
  'con_acc_desc.th_cap_reddit' => '',
  'con_acc_desc.th_cap_spotify' => '',
  'con_acc_desc.th_cap_stackexchange' => '',
  'con_acc_desc.th_cap_steam' => '',
  'con_acc_desc.th_cap_twitch' => '',
  'con_acc_desc.th_cap_vimeo' => '',
  'con_acc_desc.th_cap_vk' => '',
  'con_acc_desc.x' => '',
  'con_acc_desc.xenforo' => '',
  'con_acc_desc.yahoo' => '',
);