<?php
return array (
  'con_acc.apple' => 'Apple',
  'con_acc.facebook' => 'Facebook',
  'con_acc.github' => 'GitHub',
  'con_acc.google' => 'Google',
  'con_acc.linkedin' => 'Linkedin',
  'con_acc.microsoft' => 'Microsoft',
  'con_acc.th_cap_amazon' => 'Amazon',
  'con_acc.th_cap_amazoncognito' => 'Amazon Cognito',
  'con_acc.th_cap_apple' => 'Sign in with Apple',
  'con_acc.th_cap_battlenet' => 'BattleNet',
  'con_acc.th_cap_deviantart' => 'DeviantArt',
  'con_acc.th_cap_discord' => 'Discord',
  'con_acc.th_cap_dropbox' => 'Dropbox',
  'con_acc.th_cap_epicgames' => 'Epic Games',
  'con_acc.th_cap_imgur' => 'Imgur',
  'con_acc.th_cap_imis' => 'iMIS',
  'con_acc.th_cap_instagram' => 'Instagram',
  'con_acc.th_cap_keycloak' => 'Keycloak',
  'con_acc.th_cap_miniorange' => 'Miniorange SSO',
  'con_acc.th_cap_paypal' => 'PayPal',
  'con_acc.th_cap_pinterest' => 'Pinterest',
  'con_acc.th_cap_reddit' => 'Reddit',
  'con_acc.th_cap_spotify' => 'Spotify',
  'con_acc.th_cap_stackexchange' => 'StackExchange',
  'con_acc.th_cap_steam' => 'Steam',
  'con_acc.th_cap_twitch' => 'Twitch',
  'con_acc.th_cap_vimeo' => 'Vimeo',
  'con_acc.th_cap_vk' => 'VK',
  'con_acc.x' => 'X',
  'con_acc.xenforo' => 'XenForo',
  'con_acc.yahoo' => 'Yahoo',
);