<?php
return array (
  'widget.forum_overview_featured_content' => '',
  'widget.forum_overview_forum_statistics' => '',
  'widget.forum_overview_members_online' => '',
  'widget.forum_overview_share_page' => '',
  'widget.forum_overview_trending_content' => '',
  'widget.latest_followed_profile_posts' => 'Latest profile posts by followers',
  'widget.latest_posts' => 'Latest posts',
  'widget.latest_profile_posts' => 'Latest profile posts',
  'widget.latest_watched' => 'Latest watched',
  'widget.member_wrapper_find_member' => '',
  'widget.member_wrapper_newest_members' => '',
  'widget.online_list_online_statistics' => '',
  'widget.thuix_footer_aboutUsWidget' => 'About us',
  'widget.thuix_footer_quickNavWidget' => 'Quick navigation',
  'widget.thuix_footer_userNavWidget' => 'User menu',
  'widget.unread_posts' => 'Unread posts',
  'widget.whats_new_new_posts' => '',
  'widget.whats_new_new_profile_posts' => '',
  'widget.xa_ams_latest_comments' => '',
  'widget.xa_ams_latest_reviews' => '',
  'widget.xfes_thread_view_below_quick_reply_similar_threads' => '',
  'widget.xfmg_wrapper_trending_media' => 'Trending media',
  'widget.xfrm_list_featured_resources' => 'Featured resources',
  'widget.xfrm_list_top_resources' => '',
  'widget.xfrm_list_trending_resources' => 'Trending resources',
  'widget.xfrm_overview_latest_reviews' => '',
  'widget.xfrm_overview_statistics' => '',
  'widget.xfrm_overview_top_authors' => '',
  'widget.xfrm_whats_new_overview_new_resources' => '',
);