<?php
return array (
  'permission_interface.ahGamerProfiles' => '[AH] Gamer Profiles',
  'permission_interface.bookmarkPermissions' => 'Bookmark permissions',
  'permission_interface.conversationModeratorPermissions' => 'Direct message moderator permissions',
  'permission_interface.conversationPermissions' => 'Direct message permissions',
  'permission_interface.forumModeratorPermissions' => 'Forum moderator permissions',
  'permission_interface.forumPermissions' => 'Forum permissions',
  'permission_interface.generalModeratorPermissions' => 'General moderator permissions',
  'permission_interface.generalPermissions' => 'General permissions',
  'permission_interface.postAttachmentPermissions' => 'Post attachment permissions',
  'permission_interface.profilePostModeratorPermissions' => 'Profile post moderator permissions',
  'permission_interface.profilePostPermissions' => 'Profile post permissions',
  'permission_interface.resourceModeratorPermissions' => 'Resource moderator permissions',
  'permission_interface.resourcePermissions' => 'Resource permissions',
  'permission_interface.signaturePermissions' => 'Signature permissions',
  'permission_interface.th_uix' => 'UI.X Permissions',
  'permission_interface.xa_amsArticle' => 'AMS: Article permissions',
  'permission_interface.xa_amsArticleModerator' => 'AMS: Article moderator permissions',
  'permission_interface.xa_amsComment' => 'AMS: Comment permissions',
  'permission_interface.xa_amsCommentModerator' => 'AMS: Comment moderator permissions',
  'permission_interface.xa_amsRating' => 'AMS: Rate/Review permissions',
  'permission_interface.xa_amsRatingModerator' => 'AMS: Rate/Review moderator permissions',
  'permission_interface.xa_amsSeries' => 'AMS: Series permissions',
  'permission_interface.xa_amsSeriesModerator' => 'AMS: Series moderator permissions',
  'permission_interface.xfmgAlbum' => 'XFMG: Album permissions',
  'permission_interface.xfmgAlbumModerator' => 'XFMG: Album moderator permissions',
  'permission_interface.xfmgComment' => 'XFMG: Comment permissions',
  'permission_interface.xfmgCommentModerator' => 'XFMG: Comment moderator permissions',
  'permission_interface.xfmgMedia' => 'XFMG: Media permissions',
  'permission_interface.xfmgMediaModerator' => 'XFMG: Media moderator permissions',
  'permission_interface.xfmgNote' => 'XFMG: Note permissions',
  'permission_interface.xfmgNoteModerator' => 'XFMG: Note moderator permissions',
  'permission_interface.xfmgUploadQuotas' => 'XFMG: Upload quotas',
);