<?php
# This file was automatically generated by the MediaWiki 1.44.2
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}




## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "The DataVerse";
$wgMetaNamespace = "DataVerse";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://wiki.test";
$wgCanonicalServer = "https://wiki.test";
## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
    '1x'   => "$wgResourceBasePath/branding/wiki-logo.png",
    '2x'   => "$wgResourceBasePath/branding/wiki-logo@2x.png",
    'icon' => "$wgResourceBasePath/branding/wiki-icon.png"
];

## UPO means: this is also a user preference option


$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "wiki";
$wgDBuser = "root";
$wgDBpassword = "";

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "en";

# Time zone
$wgLocaltimezone = "UTC";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "456155be16284a9485789688275e1be32c96beb08d80a64f2274f1032079f22c";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "c82a6912e12cdda8";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions["*"]["edit"] = false;


## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "citizen";
$wgCitizenThemeDefault = "dark";            // ensures dark mode by default
$wgCitizenEnablePreferences = true;        // hide/remove the theme toggle/preferences

#This disables all footer icons (MediaWiki, CC license badges, etc.)
$wgFooterIcons = [];

# --- Hard override footer links (Citizen-safe) ---
$wgFooterLinks = [
    'places' => [],
    'info'   => [],
];

$wgHooks['SkinAddFooterLinks'][] = function ( $skin, $key, &$footerlinks ) {
    if ( $key === 'places' || $key === 'info' ) {
        $footerlinks = []; // remove all links in these blocks
    }
    return true;
};

## Email settings
$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO
$wgEmergencyContact = "you@ichaa.net";
$wgPasswordSender = "wiki@ichaa.net";
$wgNoReplyAddress = "no-reply@ichaa.net";
$wgEnotifUserTalk = true;
$wgEnotifWatchlist = true;
$wgEmailAuthentication = true;

## SMTP settings
$wgSMTP = [
    'host'     => 'ssl://smtp.gmail.com', // or 'tls://smtp.gmail.com' etc
    'IDHost'   => 'ichaa.net',             // the domain name MediaWiki should identify as
    'port'     => 465,                          // 465 for SSL, 587 for TLS
    'auth'     => true,
    'username' => 'footmouthkick@gmail.com',
    'password' => 'anrfwrfcyzubdwjg',
];

$wgCitizenThemeFeatures = [
    'breadcrumbs' => true,
];

$wgNamespacesWithSubpages[NS_MAIN] = true;

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'Citizen' );

# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'Math' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'VisualEditor' );
$wgVisualEditorEnableCategoryDialog = true;
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'PluggableAuth' );
wfLoadExtension( 'WSOAuth' );
# End of automatically generated settings.
# Add more configuration options below.

$wgPluggableAuth_Class = 'WSOAuth';
$wgPluggableAuth_EnableAutoLogin = false;

$wgWSOAuth_ConsumerKey    = 'your_client_id_here';
$wgWSOAuth_ConsumerSecret = 'your_client_secret_here';
$wgWSOAuth_AuthUri        = 'http://forum.test/forum/oauth2/authorize';
$wgWSOAuth_TokenUri       = 'http://forum.test/forum/api/oauth2/token';
$wgWSOAuth_IdentifyUri    = 'http://forum.test/forum/api/users/me';
$wgWSOAuth_CookieDomain   = '.test';
$wgWSOAuth_CookieSecure   = false; // true when you move to HTTPS
$wgWSOAuth_Scope          = 'user:read';
$wgWSOAuth_CallbackUrl    = 'http://wiki.test/index.php/Special:PluggableAuthLogin';
$wgGroupPermissions['*']['createaccount'] = false;